import {
  BarChart3,
  Bell,
  Building2,
  ClipboardCheck,
  CreditCard,
  FileText,
  History,
  Home,
  LayoutDashboard,
  Receipt,
  ShieldCheck,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "/dashboard": LayoutDashboard,
  "/dashboard/immeubles": Building2,
  "/dashboard/logements": Home,
  "/dashboard/locataires": Users,
  "/dashboard/baux": FileText,
  "/dashboard/paiements": CreditCard,
  "/dashboard/impayes": Wallet,
  "/dashboard/relances": Bell,
  "/dashboard/recus": Receipt,
  "/dashboard/depenses": Wallet,
  "/dashboard/reparations": Wrench,
  "/dashboard/documents": FileText,
  "/dashboard/demandes-visite": ClipboardCheck,
  "/dashboard/validations": ShieldCheck,
  "/dashboard/mes-demandes": ClipboardCheck,
  "/dashboard/historique": History,
  "/dashboard/rapports": BarChart3,
  "/dashboard/utilisateurs": Users,
  "/dashboard/proprietaires": Building2,
  "/dashboard/notifications": Bell,
  "/espace-locataire": LayoutDashboard,
  "/espace-locataire/mon-logement": Home,
  "/espace-locataire/mon-contrat": FileText,
  "/espace-locataire/paiements": CreditCard,
  "/espace-locataire/recus": Receipt,
  "/espace-locataire/impayes": Wallet,
  "/espace-locataire/reparations": Wrench,
  "/espace-locataire/documents": FileText,
  "/espace-locataire/messages": Bell,
  "/espace-locataire/notifications": Bell,
};

export function getNavIcon(href: string): LucideIcon {
  return ICONS[href] ?? LayoutDashboard;
}
